#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking your project before committing 🕵🏻‍♀️";

npx lint-staged || (
    echo "❌ Failed! Some errors or warning were found. ☠️ ❌";
    false;
)

echo "Everything is 🆗. I am committing your changes. ✅";
